Go
Create Database Ticket_Tracking_System
Go
Use Ticket_Tracking_System
Go
Create Table EMPLOYEE
(
	EID NVARCHAR(10) PRIMARY KEY,
	Employee_Name NVARCHAR(50),
	Hire_Date DATE,
	Dept NVARCHAR(10)
)

Go
INSERT INTO EMPLOYEE VALUES ('E100100', 'Venkat', '2004-1-10','MGM')
INSERT INTO EMPLOYEE VALUES ('E100101', 'Krishna', '2004-1-10','MGM')
INSERT INTO EMPLOYEE VALUES ('E100102', 'Chandrashekhar', '2005-3-11','DEV')
INSERT INTO EMPLOYEE VALUES ('E100103', 'Saheer Ali Khan', '2008-10-13','DEV')
INSERT INTO EMPLOYEE VALUES ('E100104', 'Shashikanth', '2007-2-17','DEV')
INSERT INTO EMPLOYEE VALUES ('M100103', 'Avinash', '2007-3-10','DEVOPS')
INSERT INTO EMPLOYEE VALUES ('M100105', 'Ashok', '2008-6-18','DEVOPS')

Go
CREATE TABLE EMPLOYEEAUTHENTICATION
(
	EID NVARCHAR(10) FOREIGN KEY REFERENCES EMPLOYEE(EID),
	User_ID NVARCHAR(20) NOT NULL,
	Password NVARCHAR(20) NOT NULL
)

GO
INSERT INTO EMPLOYEEAUTHENTICATION VALUES ('E100100', 'Venkat', 'venkat@123')
INSERT INTO EMPLOYEEAUTHENTICATION VALUES ('E100101', 'Krishna', 'krishna@123')
INSERT INTO EMPLOYEEAUTHENTICATION VALUES ('E100102', 'Chandrashekhar', 'chandrashekhar@123')
INSERT INTO EMPLOYEEAUTHENTICATION VALUES ('E100103', 'Saheer Ali Khan', 'Saheer@123')
INSERT INTO EMPLOYEEAUTHENTICATION VALUES ('E100104', 'Shashikanth', 'shashi@123')
INSERT INTO EMPLOYEEAUTHENTICATION VALUES ('M100103', 'Avinash', 'avinash@123')
INSERT INTO EMPLOYEEAUTHENTICATION VALUES ('M100105', 'Ashok', 'ashok@123')

Go
CREATE TABLE TICKET
(
	TICKET_ID INT IDENTITY(1,1) PRIMARY KEY,
	LOGGED_BY NVARCHAR(10) FOREIGN KEY REFERENCES EMPLOYEE(EID),
	RAISED_DATE DATETIME,
	SEVERITY NVARCHAR(10),
	TICKET_DESC NVARCHAR(200),
	RESOLVED_BY NVARCHAR(10) FOREIGN KEY REFERENCES EMPLOYEE(EID),
	RESOLUTION NVARCHAR(200),
	RESOLVED_DATE DATETIME,
	STATUS NVARCHAR(10)
)

Go
INSERT INTO TICKET VALUES ('E100100','2012-10-3','Major','App server not working','M100103','Need to restart with lan cable', '2012-10-4','CLOSED')
INSERT INTO TICKET VALUES ('E100104','2013-7-10','Critical','Laptop restart problem',NULL,NULL, NULL,'OPEN')

GO
CREATE TABLE Dept_Value
(
	Dept_Id INT IDENTITY(1,1) PRIMARY KEY,
	Dept NVARCHAR(10) UNIQUE NOT NULL
)
GO

CREATE FUNCTION FN_TICKET_TURNOVER_TIME() RETURNS @TICKETTABLE TABLE(
		EMPNAME NVARCHAR(20),
		TICKEDID INT,
		SEVERITY NVARCHAR(10),
		TIMETAKEN FLOAT,
		TICKETDESC NVARCHAR(200),
		RESOLVEDBY NVARCHAR(20)
	)
AS
BEGIN
	INSERT INTO @TICKETTABLE
	SELECT E.EMPLOYEE_NAME, T.TICKET_ID, T.SEVERITY, DATEDIFF(HH,T.RAISED_DATE,T.RESOLVED_DATE), T.TICKET_DESC, ER.Employee_Name FROM TICKET AS T
	INNER JOIN EMPLOYEE AS E
	ON E.EID = T.LOGGED_BY
	INNER JOIN EMPLOYEE AS ER
	ON ER.EID = T.RESOLVED_BY
	WHERE T.STATUS = 'CLOSED'

	RETURN
END
Go

ALTER VIEW ViewTicket
AS
	SELECT E.EMPLOYEE_NAME [EMP NAME], T.TICKET_ID, T.SEVERITY, CAST(DATEDIFF(HH,T.RAISED_DATE,T.RESOLVED_DATE) As nvarchar) + ':' +  CAST(DATEDIFF(MI,T.RAISED_DATE,T.RESOLVED_DATE) % 1440 As nvarchar) [TIME TAKEN], T.TICKET_DESC, ER.Employee_Name [RESOLVED BY] FROM TICKET AS T
	INNER JOIN EMPLOYEE AS E
	ON E.EID = T.LOGGED_BY
	INNER JOIN EMPLOYEE AS ER
	ON ER.EID = T.RESOLVED_BY
	WHERE T.STATUS = 'CLOSED'
GO